server:
  servlet:
    context-path: /api
  error:
    include-binding-errors: always
    include-message: always



logging:
  level:
    root: info

spring:
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /docs
  default-produces-media-type: application/json